version: '3'

networks:
  api:

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./local-env/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - api

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: ./local-env/php.dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - api

  composer:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: tail -f /dev/null
    depends_on:
      - php

  artisan:
    build:
      context: .
      dockerfile: ./local-env/php.dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: tail -f /dev/null
    networks:
      - api
